inputs:
    dirname: null # leave null if not common for all input files
    filenames: [
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_occu/eff/eff_med_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_occu/eff/eff_med_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_low_occu/eff/eff_med_low_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_low_occu/eff/eff_med_low_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_med_occu/eff/eff_med_med_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_med_occu/eff/eff_med_med_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_high_occu/eff/eff_med_high_occu_00.root,
        /home/wuct/ALICE/local/Results/BDT/k3050/third_app/occu/cutvar_med_high_occu/eff/eff_med_high_occu_00.root
    ]

    objectnames: [hEffPrompt, hEffFD, hEffPrompt, hEffFD, hEffPrompt, hEffFD, hEffPrompt, hEffFD] # can be either histograms of graphs or a mix of them; they will be drawn in the current order

output: 
    filename: /home/wuct/ALICE/local/Results/BDT/k3050/third_app/diff_occu/efficiency # with path and w/o extension
    extensions: [pdf, root] # possibilities: pdf, eps, png, root

options:
    ROOTobject: [TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1, TH1] # TH1 or TGraph: no need to specify TH1F, TH1D or TGraphErrors, TGraphAsymmErrors
    scale: [1., 1., 1., 1., 1., 1., 1., 1., 1.]
    lambdaParams: [1., 1., 1., 1., 1., 1., 1., 1., 1.] # counts -> (counts - 1) * lambda + 1
    normalize: [false, false, false, false, false, false, false, false, false] # divide histogram by its area
    colors: [kBlack, kBlack, kRed+1,  kRed+1, kAzure+47,kAzure+47, kOrange+7,   kOrange+7, kBlack, kBlack, kRed+1, kRed+1, kAzure+4, kGreen+2, kOrange+7, kMagenta+1, kBlue, kCyan+3, kSpring-5]
    markers: [kFullCircle, kOpenSquare, kFullCircle, kOpenSquare, kFullCircle, kOpenSquare, kFullCircle, kOpenSquare, kFullCircle, kFullCircle, kFullSquare, kFullSquare, kFullSquare, kFullSquare, kFullSquare]
    markersize: 1.5
    linewidth: 3
    fillstyle: [1,1,1,1,1,1,1,1,1]
    fillalpha: [1,1,1,1,1,1,1,1,1]
    drawopt: [p, p, p, p, p, p, p, p, p]
    
    ratio: 
        enable: false
        uncertainties:
            enable: false
            corr: false
        displayRMS: true
        multiRatio: false
        indexNumerator: [0, 2]
        indexDenominator: [1, 3]

    errcomp: # comparison of uncertainties
        enable: false
        relative: true

    legend:
        avoid: false #set true to avoid the legend in the final plot
        xlimits: [0.2, 0.9]
        ylimits: [0.8, 0.9]
        header: null
        # titles: [prompt pass4, fd pass4, prompt pass3, fd pass3]
        titles: [inte prompt, inte fd, low prompt, low fd, med prompt, med fd, high prompt, high fd]
        # titles: [raw yield, raw yield sim. fit]
        # titles: [corr. strategy, uncorr. strategy, combined strategy]
        options: [lp, lp, lp, lp, lp, lp, lp, lp, lp]
        textsize: 0.035
        ncolumns: 2

    text:
        x: [0.6, 0.8]
        y: [0.6, 0.9]
        text: "Pass4"
        textsize: 0.04
        textfont: 42
        textalign: 12

    canvas:
        width: 1080
        heigth: 1080
        xaxistitle: '#it{p}_{T} (GeV/#it{c})'
        yaxistitle: 'Efficiency (w. ptWeights)'
        # yaxistitle: 'Inclusive D^{0} v_{2}'
        # yaxistitle: 'Raw yield'
        xlimits: [0.3, 26]
        ylimits: [0.0001, 0.3]
        ylimitsratio: [0., 2.1]
        ylimitserr: [0., 0.35]
        logy: true
        logx: false
        ratio:
            logy: false
            logx: false
        errcomp:
            logy: false
            logx: false  
